- name: Install and configure Homeserver
  hosts: all
  become: true
  roles:
    - role: system

    - role: traefik
    - role: watchtower
    - role: homepage

    - role: loki
    - role: grafana
    - role: prometheus
    - role: uptime

    - role: authelia
