- name: Install and configure Homeserver
  hosts: all
  become: true
  roles:
    - role: system

    - role: traefik
    - role: watchtower
    - role: glances
    - role: homepage
    - role: wireguard

    - role: loki
    - role: grafana
    - role: prometheus
    - role: uptime

    - role: authelia

    - role: jellyfin
    - role: jellyseerr
    - role: audiobookshelf

    - role: sabnzbd
    - role: sonarr
    - role: radarr

    - role: redis
    - role: paperless

    - role: wallos
    - role: homeassistant
