- name: Start jellyseerr
  when: jellyseerr_enabled is true
  block:
    - name: Ensure jellyseerr config / data directories
      ansible.builtin.file:
        path: "{{ config_path }}/jellyseerr"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"

    - name: Start jellyseerr container
      community.docker.docker_container:
        name: "{{ jellyseerr_container_name }}"
        image: "{{ jellyseerr_image_name }}:{{ jellyseerr_image_version }}"
        volumes:
          - "{{ config_path }}/jellyseerr:/app/config"
        env:
          TZ: "{{ timezone }}"
          PUID: "{{ docker_user_id }}"
          PGID: "{{ docker_user_id }}"
        labels:
          traefik.enable: "true"
          traefik.http.routers.jellyseerr.entrypoints: "websecure"
          traefik.http.routers.jellyseerr.rule: "Host(`{{ jellyseerr_container_name }}.{{ hostname }}`)"
          homepage.group: "Media"
          homepage.name: "Jellyseer"
          homepage.icon: "jellyseerr.svg"
          homepage.href: "https://{{ jellyseerr_container_name }}.{{ hostname }}"
          homepage.description: "Request and manage TV shows."
          homepage.widget.type: "jellyseerr"
          homepage.widget.url: "http://{{ jellyseerr_container_name }}:5055"
          homepage.widget.key: "{{ jellyseer_api_key }}"
        networks: "{{ docker_common_settings.networks }}"
        log_driver: "{{ docker_common_settings.log_driver }}"
        log_options: "{{ docker_common_settings.log_options }}"
        restart_policy: "{{ docker_common_settings.restart_policy }}"
        user: "{{ docker_common_settings.user }}"

- name: Stop jellyseerr
  when: jellyseerr_enabled is false
  block:
    - name: Stop jellyseerr container
      community.docker.docker_container:
        name: "{{ jellyseerr_container_name }}"
        state: absent
