- name: Start homepage
  when: homepage_enabled is true
  block:
    - name: Ensure homepage config directory
      ansible.builtin.file:
        path: "{{ config_path }}/homepage/images"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"

    - name: Copy homepage static files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"
      loop:
        - src: "files/static/"
          dest: "{{ config_path }}/homepage/"
        - src: "files/images/"
          dest: "{{ config_path }}/homepage/images/"

    - name: Template homepage configuration
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"
      loop:
        - src: widgets.yml.j2
          dest: "{{ config_path }}/homepage/widgets.yaml"
        - src: settings.yml.j2
          dest: "{{ config_path }}/homepage/settings.yaml"
        - src: services.yml.j2
          dest: "{{ config_path }}/homepage/services.yaml"
        - src: bookmarks.yml.j2
          dest: "{{ config_path }}/homepage/bookmarks.yaml"

    - name: Start homepage container
      community.docker.docker_container:
        name: "{{ homepage_container_name }}"
        image: "{{ homepage_image_name }}:{{ homepage_image_version }}"
        restart_policy: unless-stopped
        volumes:
          - "{{ config_path }}/homepage:/app/config"
          - "{{ config_path }}/homepage/images:/app/public/images"
          - "{{ docker_socket }}:/var/run/docker.sock:ro"
        networks:
          - name: "{{ docker_network_name }}"
        labels:
          traefik.http.routers.homepage.entrypoints: websecure
          traefik.http.routers.homepage.rule: Host(`{{ hostname }}`)

- name: Stop homepage
  when: homepage_enabled is false
  block:
    - name: Stop homepage container
      community.docker.docker_container:
        name: "{{ homepage_container_name }}"
        state: absent
