- name: Update the packages and configure auto-updates
  ansible.builtin.include_tasks: setup.yml

- name: Install docker
  ansible.builtin.include_tasks: docker.yml

- name: Configure the firewall
  ansible.builtin.include_tasks: firewall.yml

- name: Configure Fail2Ban
  ansible.builtin.include_tasks: fail2ban.yml

- name: Configure the user account
  ansible.builtin.include_tasks: user.yml

- name: Configure secure ssh
  ansible.builtin.include_tasks: ssh.yml
