loki_enabled: true

loki_container_name: "loki"
loki_image_name: "grafana/loki"
loki_image_version: "latest"

loki_hostname: "loki"
loki_http_port: "3100"

loki_logging_driver: "loki"
loki_logging_options:
  loki-url: "https://{{ loki_container_name }}.{{ hostname }}/loki/api/v1/push"
  mode: non-blocking
  max-buffer-size: 4m
  loki-retries: "3"
  loki-pipeline-stages: |
    - regex:
        expression: '(level|lvl|severity)=(?P<level>\w+)'
    - labels:
        level:
