- name: Start authelia
  when: authelia_enabled is true
  block:
    - name: Ensure authelia config directory
      ansible.builtin.file:
        path: "{{ config_path }}/authelia"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"

    - name: Template authelia configuration
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"
      loop:
        - src: "configuration.yml.j2"
          dest: "{{ config_path }}/authelia/configuration.yml"
        - src: "users_database.yml.j2"
          dest: "{{ config_path }}/authelia/users_database.yml"

    - name: Start authelia container
      community.docker.docker_container:
        name: "{{ authelia_container_name }}"
        image: "{{ authelia_image_name }}:{{ authelia_image_version }}"
        volumes:
          - "{{ config_path }}/authelia:/config"
        env:
          TZ: "{{ timezone }}"
        labels:
          traefik.enable: "true"
          traefik.http.routers.authelia.entrypoints: websecure
          traefik.http.routers.authelia.rule: Host(`{{ authelia_container_name }}.{{ hostname }}`)
        networks: "{{ docker_common_settings.networks }}"
        # log_driver: "{{ docker_common_settings.log_driver }}"
        # log_options: "{{ docker_common_settings.log_options }}"
        restart_policy: "{{ docker_common_settings.restart_policy }}"
        user: "{{ docker_common_settings.user }}"

- name: Stop authelia
  when: authelia_enabled is false
  block:
    - name: Stop authelia container
      community.docker.docker_container:
        name: "{{ authelia_container_name }}"
        state: absent
