system_deb_architecture:
  {
    "armv6l": "armhf",
    "armv7l": "armhf",
    "aarch64": "arm64",
    "x86_64": "amd64",
    "i386": "i386",
    "armhf": "armel",
    "armel": "armel",
  }

system_docker_network_name: "default"
